# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان العقد (عربي)')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان العقد (إنجليزي)')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية العقد')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('renewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التجديد')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد')),
                ('notes_ar', models.TextField(blank=True, null=True, verbose_name='ملاحظات (عربي)')),
                ('notes_en', models.TextField(blank=True, null=True, verbose_name='ملاحظات (إنجليزي)')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
            },
        ),
    ]
