# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_ar', models.TextField(blank=True, verbose_name='التفاصيل (عربي)')),
                ('detail_en', models.TextField(blank=True, verbose_name='التفاصيل (إنجليزي)')),
                ('apply_template', models.BooleanField(default=True, help_text='استخدام نص التلقائي من السبب', verbose_name='تطبيق القالب')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('level', models.CharField(choices=[('first', 'إنذار أول'), ('second', 'إنذار ثاني'), ('disciplinary', 'إجراء تأديبي')], default='first', max_length=20, verbose_name='مستوى الإنذار')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='alerts/attachments/', verbose_name='المرفق')),
            ],
            options={
                'verbose_name': 'إنذار',
                'verbose_name_plural': 'الإنذارات',
            },
        ),
        migrations.CreateModel(
            name='AlertReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('label_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('label_en', models.CharField(max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('template_ar', models.TextField(verbose_name='قالب الرسالة (عربي)')),
                ('template_en', models.TextField(verbose_name='قالب الرسالة (إنجليزي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سبب الإنذار',
                'verbose_name_plural': 'أسباب الإنذارات',
            },
        ),
    ]
