# Generated by Django 4.2.30 on 2026-04-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ar', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('is_omani', models.BooleanField(default=False)),
                ('hire_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
