# Generated by Django 4.2.30 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name_ar',
            field=models.CharField(max_length=100, verbose_name='الاسم عربي'),
        ),
    ]
