# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name_ar', models.CharField(max_length=200, verbose_name='الاسم القانوني (عربي)')),
                ('legal_name_en', models.CharField(max_length=200, verbose_name='الاسم القانوني (إنجليزي)')),
                ('commercial_registration', models.CharField(max_length=50, unique=True, verbose_name='رقم السجل التجاري')),
                ('cr_expiry', models.DateField(verbose_name='تاريخ انتهاء السجل')),
                ('cr_file', models.FileField(blank=True, null=True, upload_to='companies/cr/', verbose_name='ملف السجل التجاري')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان (عربي)')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='العنوان (إنجليزي)')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
    ]
