# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم (إنجليزي)')),
            ],
            options={
                'verbose_name': 'نوع المستند',
                'verbose_name_plural': 'أنواع المستندات',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_docs/', verbose_name='الملف')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الملف')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_auto_renewed', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('renewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التجديد')),
                ('notes_ar', models.TextField(blank=True, verbose_name='ملاحظات (عربي)')),
                ('notes_en', models.TextField(blank=True, verbose_name='ملاحظات (إنجليزي)')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype', verbose_name='نوع الوثيقة')),
            ],
            options={
                'verbose_name': 'وثيقة موظف',
                'verbose_name_plural': 'وثائق الموظفين',
            },
        ),
    ]
