# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50, unique=True, verbose_name='رقم تصريح العمل')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('work_permit_file', models.FileField(blank=True, null=True, upload_to='work_permits/', verbose_name='ملف تصريح العمل')),
                ('is_auto_renewed', models.BooleanField(default=False, verbose_name='يتجدد تلقائياً')),
                ('renewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التجديد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تصريح عمل',
                'verbose_name_plural': 'تصاريح العمل',
            },
        ),
        migrations.CreateModel(
            name='ResidenceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='رقم بطاقة الإقامة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('card_file', models.FileField(blank=True, null=True, upload_to='residence_cards/', verbose_name='ملف بطاقة الإقامة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بطاقة إقامة',
                'verbose_name_plural': 'بطاقات الإقامة',
            },
        ),
    ]
