# Generated by Django 4.2.29 on 2026-04-07 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ar', models.CharField(max_length=100, verbose_name='الاسم الأول (عربي)')),
                ('first_name_en', models.CharField(max_length=100, verbose_name='الاسم الأول (إنجليزي)')),
                ('middle_name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأوسط (عربي)')),
                ('middle_name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأوسط (إنجليزي)')),
                ('last_name_ar', models.CharField(max_length=100, verbose_name='اللقب (عربي)')),
                ('last_name_en', models.CharField(max_length=100, verbose_name='اللقب (إنجليزي)')),
                ('nationality_ar', models.CharField(max_length=100, verbose_name='الجنسية (عربي)')),
                ('nationality_en', models.CharField(max_length=100, verbose_name='الجنسية (إنجليزي)')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('id_expiry', models.DateField(verbose_name='تاريخ انتهاء الهوية')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجواز')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('marital_status_ar', models.CharField(blank=True, max_length=100, verbose_name='الحالة الاجتماعية (عربي)')),
                ('marital_status_en', models.CharField(blank=True, max_length=100, verbose_name='الحالة الاجتماعية (إنجليزي)')),
                ('mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(\\+968)?(9|7)\\d{7}$')], verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
    ]
