# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('body_ar', models.TextField(blank=True, verbose_name='المحتوى (عربي)')),
                ('body_en', models.TextField(blank=True, verbose_name='المحتوى (إنجليزي)')),
                ('is_for_all', models.BooleanField(default=False, verbose_name='إرسال للكل')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employees', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='الموظفون المستهدفون')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
    ]
