# Generated by Django 4.2.29 on 2026-04-07 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='owners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_superuser': True}, related_name='owner_notifications', to=settings.AUTH_USER_MODEL, verbose_name='الملاك المستهدفون'),
        ),
    ]
